config/routes.rb
Rails.application.routes.draw do
  get 'product_groups/modify'
  get "product_groups/destroy"
  post "product_groups/getProducts" 
  post 'product_groups/removeMultipleGroups' 
  resources :product_groups

  get 'location_groups/modify'
  get "location_groups/destroy"
  post 'location_groups/getStores' 
  post 'location_groups/getStoresByCustAttr' 
  post 'location_groups/removeMultipleGroups' 
  resources :location_groups

  get "login/reset_password"
  get "login/index"
  post "login/create"
  get "login/logout"
 

  get 'worklist/index'
  get "users/modify"
  get "users/destroy"
  post "users/set_preference"
  post "users/get_location_hier"
  post "users/get_product_hier"
  resources :users

  get 'contract/new'
  get 'contract/create'
  post 'contract/getStores'
  post 'contract/getStoresByCustAttr'
  post 'contract/storeLocations'
  post 'contract/removeStore'
  post 'contract/storeLocationGroups'
  get 'contract/storeLocationGroups'
  post 'contract/createNewContract'
  get 'contract/modify'
  match 'contract/newFromScratch' => 'contract#newFromScratch' , via: [:get, :post]
  post 'contract/createNewContract'
  #post 'contract/newFromScratch'
  post 'contract/addNote'
  post 'contract/saveMarketingVehicle'
  post 'contract/priceVehicleProducts'
  post 'contract/getAllNote'
  post 'contract/getProducts'
  post 'contract/storeProducts'
  post 'contract/storeProductGroups'
  post 'contract/saveDate'
  post 'contract/getProductsGroupsHash'
  post 'contract/add_location_group'
  get 'contract/delete'
  post 'contract/create_tier'
  get 'contract/create_tier'
  #
  get 'contract/contractsMain'
  post 'contract/contractsMain'
  get 'contract/createTrial'
  post 'contract/createTierForVendor'
  post 'contract/update_tier'
  post 'contract/updatePriceVehical'
  post 'contract/breadcrumbCategory'
  post 'contract/breadcrumbBanner'
  get 'contract/modifyContractAttr'
  post 'contract/addContractAttribute'
  post 'contract/createVersion'
  
  
   get 'event_managements/destroy'
  post 'event_managements/addEvent'

  post 'pricing_guidelines/create_price_rules'
  post  'pricing_guidelines/get_price_rules'
  get 'pricing_guidelines/get_price_rules'
  post 'pricing_guidelines/create_price_grids'
  post  'pricing_guidelines/get_price_grids'
  get 'pricing_guidelines/get_price_grids'
  delete  'pricing_guidelines/destroy_price_rule'
  delete  'pricing_guidelines/destroy_price_grid'
  post  'pricing_guidelines/get_product_attribute'
  get 'pricing_guidelines/get_product_attribute'
  post  'pricing_guidelines/get_price_rules_attributes'
  get 'pricing_guidelines/get_price_rules_attributes'

  resources :pricing_guidelines


  namespace :api do
    get 'price_rules_services/addPriceRule'
  end

  namespace :api do
    get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
    get 'price_rules_services/removePriceRule'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
    get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
    get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids
  post 'price_grids/create_multiple'
  resources :price_rules
  post 'price_rules/create_multiple'

  resources :product_attributes
  resources :ad_management
  resources :custom_attributes
  resources :event_managements
  resources :price_grids
  #   root url for web app module
  root 'login#index'

end

app/models/price_grid.rb
class PriceGrid < ActiveRecord::Base
  validates :price_vehicle_id, presence: true
  validates :from_price, presence: true, if: :price_vehicle?
  validates :to_price, presence: true, if: :price_vehicle?
  validates :multiples, presence: true, if: :price_vehicle_multiples?
  
  def price_vehicle?
    price_vehicle_id !=1
  end
  def price_vehicle_multiples?
    price_vehicle_id==1
  end
  
   def self.get_price_grids(category_id,location_id)

    logger.info { "category_id2 =#{category_id}" }
    logger.info { "location_id2 =#{location_id}" }
    if (!category_id.blank? && !location_id.blank? )
      @price_grids = PriceGrid.where("location_id=#{location_id}  AND category_id=#{category_id} ")

    else if(!category_id.blank? && location_id.blank?)

        @price_grids = PriceGrid.where("category_id=#{category_id} and location_id IS NULL")

      else if(category_id.blank? && !location_id.blank?)
          @price_grids = PriceGrid.where("location_id=#{location_id} and category_id IS NULL")

        else
          @price_grids = nil

        end
      end
    end
    logger.info { "@price_grids =#{@price_grids}" }
    return @price_grids

  end
  
  
end

app/controllers/price_grids_controller.rb
# require '../AdInServices/app/models/api/location_services.rb'

class PriceGridsController < ApplicationController
  respond_to :html, :json
  ActionController::Parameters.permit_all_parameters = true
  before_action :set_price_grid, only: [:show, :edit, :update, :destroy]
  # GET /price_grids
  # GET /price_grids.json
  def index
    @price_grids = PriceGrid.all
    @price_grid = PriceGrid.new
    
    logger.info { "finally in the logger and location =#{@locations}" }
  
  end

  # GET /price_grids/1
  # GET /price_grids/1.json
  def show
    @price_grid.destroy
    redirect_to pricing_guidelines_url
    logger.info { "finally in destroy method" }
  end

  # GET /price_grids/new
  def new
    @price_grid = PriceGrid.new
  end

  # GET /price_grids/1/edit
  def edit
  end

  # POST /price_grids
  # POST /price_grids.json
  def create
    @price_grid = PriceGrid.new

    respond_to do |format|
      if @price_grid.save
        format.html { render :index, notice: 'Price grid was successfully created.' }
        format.json { render :index, status: :created, location: @price_grid }
      else
        format.html { render :new }
        format.json { render json: @price_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_grids/1
  # PATCH/PUT /price_grids/1.json
  def update
    respond_to do |format|
      if @price_grid.update(price_grid_params)
        format.html { redirect_to @price_grid, notice: 'Price grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_grid }
      else
        format.html { render :edit }
        format.json { render json: @price_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_grids/1
  # DELETE /price_grids/1.json
  def destroy
    @price_grid.destroy
    redirect_to pricing_guidelines_url
    logger.info { "finally in destroy method" }
    end
 
  # POST /price_grids
  # POST /price_grids.json
  def create_multiple
      params[:price_grid].each do |price_grid|
      price_grid=PriceGrid.create(price_grid)
      logger.info { "finally in the logger =#{price_grid}" }
    end
   redirect_to pricing_guidelines_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_price_grid
    @price_grid = PriceGrid.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_grid_params
    params.require(:price_grid).permit(:name, :description, :price_vehicle_id, :from_price, :to_price, :price_candidates, :multiples, :created_by, :updated_by)
  end

end

app/views/price_grids/_form.html.erb
<%= form_for(@price_grid) do |f| %>
  <% if @price_grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price_grid.errors.count, "error") %> prohibited this price_grid from being saved:</h2>

      <ul>
      <% @price_grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price_vehicle_id %><br>
    <%= f.number_field :price_vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :price_rule_id %><br>
    <%= f.number_field :price_rule_id %>
  </div>
  <div class="field">
    <%= f.label :from_price %><br>
    <%= f.number_field :from_price %>
  </div>
  <div class="field">
    <%= f.label :to_price %><br>
    <%= f.number_field :to_price %>
  </div>
  <div class="field">
    <%= f.label :price_candidates %><br>
    <%= f.text_field :price_candidates %>
  </div>
  <div class="field">
    <%= f.label :multiples %><br>
    <%= f.text_field :multiples %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.text_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_grids/edit.html.erb
<h1>Editing price_grid</h1>

<%= render 'form' %>

<%= link_to 'Show', @price_grid %> |
<%= link_to 'Back', price_grids_path %>

app/views/price_grids/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>jQuery Get Values of Selected Checboxes</title>
		<script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				$("button").click(function() {
					var first;
					var second;
					var Cents1;
					var Cents2;
					var favorite = [];
					$.each($("input[name='$1']:checked"), function() {
						//favorite.push($(this).val());
						first = $(this).val();

						$.each($("input[name='$2']:checked"), function() {
							//favorite.push($(this).val());
							second = $(this).val();
							$.each($("input[name='Cents1']:checked"), function() {
								//favorite.push($(this).val());
								Cents1 = $(this).val();
								$.each($("input[name='Cents2']:checked"), function() {
									Cents2 = $(this).val();
									favorite.push(first+''+second+'.'+Cents1+''+Cents2);
								});
							});
						});
					});
					alert("values are: " + favorite.join(", "));
				});
			});
			  
			  function disableList() {
			  	var number=3
			  	$.each($("input[name='$1']"), function() {
						//favorite.push($(this).val());
						first = $(this).val();
						if(first<=number)
						{
							$("input[name='$1'][value='"+first+"']").prop('disabled', true);
							alert("yes"+first);
							
						}
						});
			  	
	
}

			  
		</script>
	</head>
	<body>
		<form>
			<input id="price_grid__from_price" name="price_grid[][from_price]" type="text">
			<input id="price_grid__to_price" name="price_grid[][to_price]" type="text">
			<table>
				<h3>Select:</h3>
				<tr>
					<td>
					<tr>
						<label>
							<input type="checkbox" value="1" name="$1">
							1</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="2" name="$1">
							2</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="3" name="$1">
							3</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="4" name="$1">
							4</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="5" name="$1">
							5</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="6" name="$1">
							6</label>
					</tr>
					<br>
					</td>

					<td>
					<tr>
						<label>
							<input type="checkbox" value="1" name="$2">
							1</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="2" name="$2">
							2</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="3" name="$2">
							3</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="4" name="$2">
							4</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="5" name="$2">
							5</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="6" name="$2">
							6</label>
					</tr>
					<br>
					</td>

					<td>
					<tr>
						<label>
							<input type="checkbox" value="1" name="Cents1">
							1</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="2" name="Cents1">
							2</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="3" name="Cents1">
							3</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="4" name="Cents1">
							4</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="5" name="Cents1">
							5</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="6" name="Cents1">
							6</label>
					</tr>
					<br>
					</td>

					<td>
					<tr>
						<label>
							<input type="checkbox" value="1" name="Cents2">
							1</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="2" name="Cents2">
							2</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="3" name="Cents2">
							3</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="4" name="Cents2">
							4</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="5" name="Cents2">
							5</label>
					</tr>
					<tr>
						<label>
							<input type="checkbox" value="6" name="Cents2">
							6</label>
					</tr>
					<br>
					</td>
				</tr>
				<button type="button">
					Get Values
				</button>
			</table>
		</form>
		
		
		<button type="button" onclick="disableList()">
					Disable Values
		</button>
	</body>
</html>

app/views/price_grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price_grid.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @price_grid.description %>
</p>

<p>
  <strong>Price vehicle:</strong>
  <%= @price_grid.price_vehicle_id %>
</p>



<p>
  <strong>From price:</strong>
  <%= @price_grid.from_price %>
</p>

<p>
  <strong>To price:</strong>
  <%= @price_grid.to_price %>
</p>

<p>
  <strong>Price candidates:</strong>
  <%= @price_grid.price_candidates %>
</p>

<p>
  <strong>Multiples:</strong>
  <%= @price_grid.multiples %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @price_grid.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @price_grid.updated_by %>
</p>

<%= link_to 'Edit', edit_price_grid_path(@price_grid) %> |
<%= link_to 'Back', price_grids_path %>