config/routes.rb
Rails.application.routes.draw do
  get 'product_groups/modify'
  get "product_groups/destroy"
  post "product_groups/getProducts" 
  post 'product_groups/removeMultipleGroups' 
  resources :product_groups

  get 'location_groups/modify'
  get "location_groups/destroy"
  post 'location_groups/getStores' 
  post 'location_groups/getStoresByCustAttr' 
  post 'location_groups/removeMultipleGroups' 
  resources :location_groups

  get "login/reset_password"
  get "login/index"
  post "login/create"
  get "login/logout"
 

  get 'worklist/index'
  get "users/modify"
  get "users/destroy"
  post "users/set_preference"
  post "users/get_location_hier"
  post "users/get_product_hier"
  resources :users

  get 'contract/new'
  get 'contract/create'
  post 'contract/getStores'
  post 'contract/getStoresByCustAttr'
  post 'contract/storeLocations'
  post 'contract/removeStore'
  post 'contract/storeLocationGroups'
  get 'contract/storeLocationGroups'
  post 'contract/createNewContract'
  get 'contract/modify'
  match 'contract/newFromScratch' => 'contract#newFromScratch' , via: [:get, :post]
  post 'contract/createNewContract'
  #post 'contract/newFromScratch'
  post 'contract/addNote'
  post 'contract/saveMarketingVehicle'
  post 'contract/priceVehicleProducts'
  post 'contract/getAllNote'
  post 'contract/getProducts'
  post 'contract/storeProducts'
  post 'contract/storeProductGroups'
  post 'contract/saveDate'
  post 'contract/getProductsGroupsHash'
  post 'contract/add_location_group'
  get 'contract/delete'
  post 'contract/create_tier'
  get 'contract/create_tier'
  #
  get 'contract/contractsMain'
  post 'contract/contractsMain'
  get 'contract/createTrial'
  post 'contract/createTierForVendor'
  post 'contract/update_tier'
  post 'contract/updatePriceVehical'
  post 'contract/breadcrumbCategory'
  post 'contract/breadcrumbBanner'
  get 'contract/modifyContractAttr'
  post 'contract/addContractAttribute'
  post 'contract/createVersion'
  
  
   get 'event_managements/destroy'
  post 'event_managements/addEvent'

  post 'pricing_guidelines/create_price_rules'
  post  'pricing_guidelines/get_price_rules'
  get 'pricing_guidelines/get_price_rules'
  post 'pricing_guidelines/create_price_grids'
  post  'pricing_guidelines/get_price_grids'
  get 'pricing_guidelines/get_price_grids'
  delete  'pricing_guidelines/destroy_price_rule'
  delete  'pricing_guidelines/destroy_price_grid'
  post  'pricing_guidelines/get_product_attribute'
  get 'pricing_guidelines/get_product_attribute'
  post  'pricing_guidelines/get_price_rules_attributes'
  get 'pricing_guidelines/get_price_rules_attributes'

  resources :pricing_guidelines


  namespace :api do
    get 'price_rules_services/addPriceRule'
  end

  namespace :api do
    get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
    get 'price_rules_services/removePriceRule'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
    get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
    get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids
  post 'price_grids/create_multiple'
  resources :price_rules
  post 'price_rules/create_multiple'

  resources :product_attributes
  resources :ad_management
  resources :custom_attributes
  resources :event_managements
  resources :price_grids
  #   root url for web app module
  root 'login#index'

end

app/models/price_rule.rb
class PriceRule < ActiveRecord::Base
  #validates :min_margin, presence: true
  #validates :min_price_change, presence: true
  #validates :max_price_change, presence: true
  #validates :min_passthrough, presence: true
  #validates :max_passthrough, presence: true
  #validates :optimization_goal, presence: true
  #validates :marketing_vehicle_id, presence: true
  def self.get_price_rules(category_id,location_id)

    logger.info { "category_id2 =#{category_id}" }
    logger.info { "location_id2 =#{location_id}" }
    if (!category_id.blank? && !location_id.blank? )
      @price_rules = PriceRule.where("location_id=#{location_id}  AND category_id=#{category_id} ")

    else if(!category_id.blank? && location_id.blank?)

        @price_rules = PriceRule.where("category_id=#{category_id} and location_id IS NULL")

      else if(category_id.blank? && !location_id.blank?)
          @price_rules = PriceRule.where("location_id=#{location_id} and category_id IS NULL")

        else
          @price_rules = nil

        end
      end
    end
    logger.info { "@price_rules =#{@price_rules}" }
    return @price_rules

  end

end

app/controllers/price_rules_controller.rb
require '../AdInServices/app/models/api/product_services.rb'

class PriceRulesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  respond_to :html, :json
  before_action :set_price_rule, only: [:show, :edit, :update, :destroy]
  ActionController::Parameters.permit_all_parameters = true
  # GET /price_rules
  # GET /price_rules.json
  def index
    @price_rules = PriceRule.all
    @location =Api::LocationServices.getAllBanner
    @allLocationsHierarchy = Array.new
    @location.each{|banner|
      l = Api::LocationServices.getAllSubBanners(banner)
      @allLocationsHierarchy.push(l)
    }
    @allCategoriesHierarchy = Api::ProductServices.getAllCategoriesInHash
    category_id=params[:category_id]
    if (category_id !=nil)
      @price_rules = PriceRule.where("category_id=#{category_id}")
      respond_to do |format|
        format.json { render json: @price_rules, status: :ok }
        format.js
        logger.info { "finally in the logger =#{@response}" }
      end
    else
      @price_rules = PriceRule.all
    end

  end

  # GET /price_rules/1

  # GET /price_rules/1.json
  def show
  end

  # GET /price_rules/new

  def new
    @price_rule = PriceRule.new
  end

  # GET /price_rules/1/edit

  def edit
  end

  # POST /price_rules

  # POST /price_rules.json
  def create
    @price_rule = PriceRule.new(price_rule_params)

    respond_to do |format|
      if @price_rule.save
        format.html { redirect_to @price_rule, notice: 'Price rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @price_rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @price_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_rules/1

  # PATCH/PUT /price_rules/1.json
  def update
    respond_to do |format|
      if @price_rule.update(price_rule_params)
        format.html { redirect_to @price_rule, notice: 'Price rule was successfully updated.' }
        format.json { respond_with_bip(@price_rule) }
      else
        format.html { render action: 'edit' }
        format.json { respond_with_bip(@price_rule) }
      end
    end
  end

  # DELETE /price_rules/1

  # DELETE /price_rules/1.json
  def destroy
    @price_rule.destroy
    respond_to do |format|
      format.html { redirect_to price_rules_url }
      format.json { head :no_content }
    end
  end

  # POST /price_rules

  # POST /price_rules.json
  def create_multiple
    params[:price_rule].each do |price_rule|
      price_rule=PriceRule.create(price_rule)
      logger.info { "finally in the logger =#{price_rule}" }
    end
    redirect_to price_rules_url
  end

  # POST /price_rules
  # POST /price_rules.json

  def get_rules
    category_id=params[:category_id]
    if (category_id !=nil)
      @price_rules = PriceRule.where("category_id=#{category_id}")
      respond_to do |format|
        format.json { render json: @price_rules, status: :ok }
        format.js
        logger.info { "finally in the logger =#{@response}" }
      end
    else
      @price_rules = PriceRule.all
      format.json { render json: @price_rules, status: :ok }
      format.js
      logger.info { "finally in the logger =#{@response}" }
    end
  end
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_price_rule
    @price_rule = PriceRule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_rule_params
    params.require(:price_rule).permit(:name, :description, :marketing_vehicle_id, :location_id, :min_margin, :max_margin, :max_passthrough, :optimization_goal, :category_id, :min_passthrough, :min_price_change, :max_price_change)
  end
end

app/helpers/price_rules_helper.rb
module PriceRulesHelper
end

app/views/price_rules/_form.html.erb
<%= form_for(@price_rule) do |f| %>
  <% if @price_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price_rule.errors.count, "error") %> prohibited this price_rule from being saved:</h2>

      <ul>
      <% @price_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :marketing_vehicle_id %><br>
    <%= f.number_field :marketing_vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :banner_id %><br>
    <%= f.number_field :banner_id %>
  </div>
  <div class="field">
    <%= f.label :min_margin %><br>
    <%= f.number_field :min_margin %>
  </div>
  <div class="field">
    <%= f.label :max_margin %><br>
    <%= f.number_field :max_margin %>
  </div>
  <div class="field">
    <%= f.label :max_passthrough %><br>
    <%= f.number_field :max_passthrough %>
  </div>
  <div class="field">
    <%= f.label :optimization_goal %><br>
    <%= f.text_field :optimization_goal %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :min_passthrough %><br>
    <%= f.number_field :min_passthrough %>
  </div>
  <div class="field">
    <%= f.label :min_price_change %><br>
    <%= f.number_field :min_price_change %>
  </div>
  <div class="field">
    <%= f.label :max_price_change %><br>
    <%= f.number_field :max_price_change %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_rules/edit.html.erb
<h1>Editing price_rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @price_rule %> |
<%= link_to 'Back', price_rules_path %>

app/views/price_rules/new.html.erb
<h1>New price_rule</h1>

<%= render 'form' %>

<%= link_to 'Back', price_rules_path %>

app/views/price_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price_rule.name %>
</p>

<p>
  <strong>Varying:</strong>
  <%= @price_rule.varying %>
</p>

<p>
  <strong>Description:</strong>
  <%= @price_rule.description %>
</p>

<p>
  <strong>Marketing vehicle:</strong>
  <%= @price_rule.marketing_vehicle_id %>
</p>

<p>
  <strong>Banner:</strong>
  <%= @price_rule.banner_id %>
</p>

<p>
  <strong>Min margin:</strong>
  <%= @price_rule.min_margin %>
</p>

<p>
  <strong>Max margin:</strong>
  <%= @price_rule.max_margin %>
</p>

<p>
  <strong>Max passthrough:</strong>
  <%= @price_rule.max_passthrough %>
</p>

<p>
  <strong>Optimization goal:</strong>
  <%= @price_rule.optimization_goal %>
</p>

<p>
  <strong>Varying:</strong>
  <%= @price_rule.varying %>
</p>

<p>
  <strong>Category:</strong>
  <%= @price_rule.category_id %>
</p>

<p>
  <strong>Min passthrough:</strong>
  <%= @price_rule.min_passthrough %>
</p>

<p>
  <strong>Min price change:</strong>
  <%= @price_rule.min_price_change %>
</p>

<p>
  <strong>Max price change:</strong>
  <%= @price_rule.max_price_change %>
</p>

<%= link_to 'Edit', edit_price_rule_path(@price_rule) %> |
<%= link_to 'Back', price_rules_path %>