config/routes.rb
Rails.application.routes.draw do
  get 'product_groups/modify'
  get "product_groups/destroy"
  post "product_groups/getProducts" 
  post 'product_groups/removeMultipleGroups' 
  resources :product_groups

  get 'location_groups/modify'
  get "location_groups/destroy"
  post 'location_groups/getStores' 
  post 'location_groups/getStoresByCustAttr' 
  post 'location_groups/removeMultipleGroups' 
  resources :location_groups

  get "login/reset_password"
  get "login/index"
  post "login/create"
  get "login/logout"
 

  get 'worklist/index'
  get "users/modify"
  get "users/destroy"
  post "users/set_preference"
  post "users/get_location_hier"
  post "users/get_product_hier"
  resources :users

  get 'contract/new'
  get 'contract/create'
  post 'contract/getStores'
  post 'contract/getStoresByCustAttr'
  post 'contract/storeLocations'
  post 'contract/removeStore'
  post 'contract/storeLocationGroups'
  get 'contract/storeLocationGroups'
  post 'contract/createNewContract'
  get 'contract/modify'
  match 'contract/newFromScratch' => 'contract#newFromScratch' , via: [:get, :post]
  post 'contract/createNewContract'
  #post 'contract/newFromScratch'
  post 'contract/addNote'
  post 'contract/saveMarketingVehicle'
  post 'contract/priceVehicleProducts'
  post 'contract/getAllNote'
  post 'contract/getProducts'
  post 'contract/storeProducts'
  post 'contract/storeProductGroups'
  post 'contract/saveDate'
  post 'contract/getProductsGroupsHash'
  post 'contract/add_location_group'
  get 'contract/delete'
  post 'contract/create_tier'
  get 'contract/create_tier'
  #
  get 'contract/contractsMain'
  post 'contract/contractsMain'
  get 'contract/createTrial'
  post 'contract/createTierForVendor'
  post 'contract/update_tier'
  post 'contract/updatePriceVehical'
  post 'contract/breadcrumbCategory'
  post 'contract/breadcrumbBanner'
  get 'contract/modifyContractAttr'
  post 'contract/addContractAttribute'
  post 'contract/createVersion'
  
  
   get 'event_managements/destroy'
  post 'event_managements/addEvent'

  post 'pricing_guidelines/create_price_rules'
  post  'pricing_guidelines/get_price_rules'
  get 'pricing_guidelines/get_price_rules'
  post 'pricing_guidelines/create_price_grids'
  post  'pricing_guidelines/get_price_grids'
  get 'pricing_guidelines/get_price_grids'
  delete  'pricing_guidelines/destroy_price_rule'
  delete  'pricing_guidelines/destroy_price_grid'
  post  'pricing_guidelines/get_product_attribute'
  get 'pricing_guidelines/get_product_attribute'
  post  'pricing_guidelines/get_price_rules_attributes'
  get 'pricing_guidelines/get_price_rules_attributes'

  resources :pricing_guidelines


  namespace :api do
    get 'price_rules_services/addPriceRule'
  end

  namespace :api do
    get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
    get 'price_rules_services/removePriceRule'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
    get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
    get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
    get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
    get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids
  post 'price_grids/create_multiple'
  resources :price_rules
  post 'price_rules/create_multiple'

  resources :product_attributes
  resources :ad_management
  resources :custom_attributes
  resources :event_managements
  resources :price_grids
  #   root url for web app module
  root 'login#index'

end

app/controllers/users_controller.rb
# require '../AdInServices/app/controllers/api/users_services_controller.rb'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :set_preference, :modify]
  skip_before_action :verify_authenticity_token
  def index
    @users = Api::UserServices.getAllUsers
  end

  def show
  end

  def new
    @user = User.new
    @allCategoriesHierarchy = ALL_CATEGORIES_IN_HASH
    @allBannersHierarchy = ALL_BANNERS_IN_HASH
  end

  def edit
    @allCategoriesHierarchy = ALL_CATEGORIES_IN_HASH
    @allBannersHierarchy = ALL_BANNERS_IN_HASH
  end
  def modify
    @allCategoriesHierarchy = ALL_CATEGORIES_IN_HASH
    @allBannersHierarchy = ALL_BANNERS_IN_HASH
    @user_categories = Api::UserServices.getAllUserCategories(@user.id)
    @user_locations = Api::UserServices.getAllUserLocations(@user.id)
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if Api::UserServices.addUser(@user, params)
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        @allCategoriesHierarchy = ALL_CATEGORIES_IN_HASH
        @allBannersHierarchy = ALL_BANNERS_IN_HASH
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if Api::UserServices.updateUser(@user, user_params, params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        @allCategoriesHierarchy = ALL_CATEGORIES_IN_HASH
        @allBannersHierarchy = ALL_BANNERS_IN_HASH
        @user_categories = Api::UserServices.getAllUserCategories(@user.id)
        @user_locations = Api::UserServices.getAllUserLocations(@user.id)
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if Api::UserServices.removeUser(@user)
       format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end
  def set_preference
    user = User.find(params[:id])
    user.update_attributes(:user_preference => params[:preference])
    respond_to do |format|
      format.json { render json: user.user_preference, status: :ok}
      format.js
    end
  end  

  def get_location_hier
    location_trail = Api::LocationGroupServices.createLocationTrail(params[:location_id]) unless params[:location_id].blank?
    location_name = Api::LocationServices.getLocationNameFromLocationTrail(location_trail)
    respond_to do |format|
      format.json {render json: location_name, status: :ok}
      format.js
    end
  end
  def get_product_hier
    product_trail = Api::ProductGroupServices.getProductTrail(params[:product_id]) unless params[:product_id].blank?
    product_name = Api::ProductServices.getCategoryNameStringFromCategoryTrail(product_trail)
    respond_to do |format|
      format.json {render json: product_name, status: :ok}
      format.js
    end
  end

  def reset_password
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.last_password_change_time < 2.hours.ago
      redirect_to root_url, :alert => "Password reset url has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset."
    else
      render :change_password, :notice => "something went wrong"
    end
  end
  def change_password
    @user = User.find_by_password_reset_token!(params[:id])
  end
  def forget_password
  end
   def send_password_reset
    user = User.find_by_email(params[:email])
    if user
      user.generate_token(:password_reset_token)
      user.update_attribute(:last_password_change_time, Time.zone.now)
      Email.recovery(user, user.email).deliver
      redirect_to root_url, :notice => "Email sent with password reset instructions."
    else
      redirect_to :back, :notice => "Your account not found"
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :parent_id, :department, :role, :last_login_time, :last_password_changed_time, :password, :password_confirmation, :status, :user_preference)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= render 'shared/form_error', :object => @user %>	  
	<div class="row">
	
		<div class="col-md-3">
		 <div class="form-group">
		   <label>User Name</label>
		   <% if @user.new_record? %>
    	     <%= f.text_field :username, :class=>"form-control"%>
    	   <% else %>
    	     <%= @user.username %>
    	     <%= hidden_field_tag "user[username]", @user.username %>
    	    <% end %> 
		 </div>
		 <div class="form-group">
		   <!--<label>User ID</label>
		   <input type="text" class="form-control" placeholder="">-->
		   <label>Email ID</label>
		    <% if @user.new_record? %>
    	      <%= f.text_field :email, :class=>"form-control" %>
    	    <% else %>
    	      <%= @user.email %>
    	      <%= hidden_field_tag "user[email]", @user.email %>
    	    <% end %> 
		 </div>
		 
		</div>
	
		<% if @user.new_record? %>
    	<div class="col-md-3">
	       <div class="form-group">
		    <label>Password</label>
		    <%= f.password_field :password, :class=>"form-control"%>
		   </div>
		   <div class="form-group">
		     <label>Password Confirmation</label>
		     <%= f.password_field :password_confirmation, :class=>"form-control"%>
		   </div>
		</div>
        <% end %>
    
		<div class="col-md-3">
	      <div class="form-group" style="visibility:hidden;">
	        <label>Role</label>
	      <%= select_tag('user[role]', options_for_select([['Admin', 1], ['Category Manager', 2]], selected: :role),:prompt=>"Select Role", :class=>"form-control") %>
	     </div>
	     <div class="form-group">
	        <label>Reporting Supervisor</label>
		<%= collection_select(:user, :parent_id, User.all, :id, :first_name, {},:prompt=>true, :include_blank=> true, :class=>"form-control") %>
	     </div>
		</div>
	</div>
	<!-- row 1 -->
	
	<div class="sectionBdr">
	<div class="row"> 

	<h2 class="heading">Select Product Hierarchy</h2>
	<div  class="col-md-3">
	<div class="right-inner-addon">
	 <i class="glyphicon glyphicon-search"></i>
	  <input type="search" class="form-control" placeholder="Quick search hierarchy & attributes" />
	  <div class="reset"><a href="#" class="reset">Reset</a></div>
	</div>

	<!-- SO tree -->
	<div class="productHeirarchyTreeDiv">
	  <span class="hierarchyHeading">Hierarchy</span>
	  <ul id="productHeirarchyTree">
		<% @allCategoriesHierarchy.each do |categoryHash| %>
		<% def ihash(h) %>
		<% h.each do |k,v| %>
		<%  if v.is_a?(Hash) %>
		<li>
		  <span onclick="setcategoryId(<%= k[0] .to_i %>)"><%= k[1] %></span>
		  <ul>
			<li>
			  <% ihash(v) %>
			</li>
		   </ul>
		</li>
		<%   else %>
		<li class="treeLastChild">
		  <span onclick="setcategoryId(<%= k[0] .to_i %>)"><%= k[1] %></span>
		</li>
		<% end %>
		<% end %>
		<% end %>
		<% ihash(categoryHash) %>
		<% end %>
	  </ul>
	</div>
	</div>
	<!-- EO tree -->

    <div class="col-md-1 pad0">
       <!-- <input type="hidden" name="category_id" id = "categoryId" value = "" > -->
       <button type="button" class="btn btn-default" id="categoryId" value= "" > Add ></button>
	   <button type="button" class="btn btn-default marginTop10">< Remove</button>
	</div>
	<div class="col-md-8">
	<table class="table-bordered categoryTable tablesorter table-striped margin0">
	 <thead>
	   <tr>
		<th><input type="checkbox" id="selectAll1"></th>
		<th>Product Hierarchy</th>
		<th>Access</th>
	   </tr>
	 </thead>
	 <tbody id="productHierselected">
	  <% unless @user.new_record? %>
	  	 <% @user_categories.each do |user_category|%>
	      <tr>
	       <td><input type="checkbox" name="selectedCateHierArray[]" class="checkbox1" id="<%= user_category.categories_hier_id%>" value="<%= user_category.categories_hier_id%>" checked="true" ></td>
	        <td><%= Api::UserServices.getUserCategoryName(user_category.categories_hier_id)%></td>
	       <td>
	         <div class="form-group"> 
	          <label class="radio-inline">
	           <input type="radio" name="locRadio" value="option1"> Read Only
	          </label>
			  <label class="radio-inline">
				<input type="radio" name="locRadio" id="inlineRadio2" value="option2"> Full Access
			  </label>
	         </div>
	       </td>
	       </tr> 
	  	  <% end %>
	  	<% end %>
	</tbody>
    </table>
    </div>

	</div>	<!-- section bdr ends -->
	<div class="clear"></div>
	</div><!-- row2 -->

	<div class="sectionBdr">
	<div class="row"> 
	<h2 class="heading">Select Location Hierarchy</h2>
	<div  class="col-md-3">
	  <div class="right-inner-addon">
		<i class="glyphicon glyphicon-search"></i>
		<input type="search" class="form-control" placeholder="Quick search hierarchy & attributes" />
		<div class="reset"><a href="#" class="reset">Reset</a></div>
	  </div>
	 <!-- SO tree -->
	  <div class="productHeirarchyTreeDiv">
	  <span class="hierarchyHeading">Hierarchy</span>
	  <ul id="locationHeirarchyTree">
	  <% if !@allBannersHierarchy.blank? %>
	    <% @allBannersHierarchy.each do |bannerHash| %>

	    <% def jhash(h) %>
	    <% h.each do |k,v| %>
	    <%  if v.is_a?(Hash) %>
	     <li>
	     <span onclick="setlocationId(<%= k[0] .to_i %>)"><%= k[1] %></span>
	      <ul>
	        <li >
	          <% jhash(v) %>
	        </li>
	      </ul>
	    </li>
	    <%   else %>
	    <li class="treeLastChild">
	      <span onclick="setlocationId(<%= k[0] .to_i %>)"><%= k[1] %></span>
	    </li>
	    <% end %>
	    <% end %>
	    <% end %>
	    <% jhash(bannerHash) %>
	    <% end %>
	  <% end %> 
	  </ul>
	</div>
	</div>
	<!-- EO tree -->
	<div class="col-md-1 pad0">
	  <!-- <input type="hidden" name="location_id" id = "locationId" value = "" > -->
	  <button type="button" class="btn btn-default" id="locationId" value= "" > Add ></button>
	  <button type="button" class="btn btn-default marginTop10">< Remove</button>
	</div>


	<div  class="col-md-8">
	<table class=" table-bordered categoryTable tablesorter table-striped margin0">
	  <thead>
         <tr>
           <th><input type="checkbox" id="selectAll2"></th>
	       <th>Location Hierarchy</th>
           <th>Access</th>
         </tr>
	  </thead>
	  <tbody id ="locationHierselected">
	  	<% unless @user.new_record? %>
	  	 <% @user_locations.each do |user_location|%>
	      <tr>
	       <td><input type="checkbox" name="selectedLocHierArray[]" class="checkbox2" id="<%= user_location.location_hier_id%>" value="<%= user_location.location_hier_id%>" checked="true" ></td>
	        <td><%= Api::UserServices.getUserLocationName(user_location.location_hier_id)%></td>
	       <td>
	         <div class="form-group"> 
	          <label class="radio-inline">
	           <input type="radio" name="locRadio" value="option1"> Read Only
	          </label>
			  <label class="radio-inline">
				<input type="radio" name="locRadio" id="inlineRadio2" value="option2"> Full Access
			  </label>
	         </div>
	       </td>
	       </tr> 
	  	  <% end %>
	  	<% end %>
	  </tbody>
	</table>
	</div>
	</div>	
	<!-- section bdr ends -->
	<div class="clear"></div>
	</div>
	<!-- row3 -->
	<div id ="hiddenDiv" style="display:none;"></div>

	<div class="row">
	 <div class="col-lg-12 ">  
	   <%= f.submit "#{@user.new_record? ? "Create" : "Update"} User", :class=>"btn btn-default" %> 
       <%= link_to 'Cancel', users_path, :class => "btn btn-link" %>
	 </div>
	</div>

	<% end %>

app/views/users/change_password.html.erb
<h1>Change Password</h1>

<%= form_for @user, :action=>"reset_password" do |f| %>
  <%= render 'shared/form_error', :object => @user %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/users/edit.html.erb
<div class="container tab-content tabContentMain"> 
	<div id="adMgmt" class="container tab-pane active worklistTabBody">
	  <div class="page-header">
		<h1><span class="glyphicon glyphicon-user"></span> User Management</h1>
	  </div>
	  <div id="breadcrumbSection">
	    <ul class="breadcrumb">
	     <li><a href="/users">User Management</a></li>
	     <li class="active">Edit User</li>
	    </ul>
	  </div>
	 <div class="row">   
	   <div class="col-md-10  marginTop10">Edit User</div>
	 </div>
     <div class="subTabContent contentSpace">
		<%= render :partial=>"form" %>
     </div>
	</div>

</div>
<script>

$(document).ready(function() 
{ 
$('#productHeirarchyTree').sapling();
$('#locationHeirarchyTree').sapling();

$('.treeLastChild,.sapling-item').click(function() {
$('.treeLastChild,.sapling-item').removeClass('selectedFilter');
$(this).addClass('selectedFilter');

var topCat = $(".sapling-item");

if(!$(this).hasClass("sapling-expanded")){
topCat.removeClass("selectedFilter") 
}
});


$('#selectAll').click(function(event) {  //on click 
if(this.checked) { // check select status
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = true;  //select all checkboxes with class "checkbox1"               
});
}else{
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = false; //deselect all checkboxes with class "checkbox1"                       
});         
}
});

}); 
</script>

app/views/users/forget_password.html.erb
<div>
<%= form_tag "/users/send_password_reset", :method => :post do %>

 <p> <label>Email:</label><br />
  <%= text_field_tag :email %><br />
</p>
  <%= submit_tag "Reset Password" %>

<% end %>
</div>

app/views/users/index.html.erb
<div class="container tab-content tabContentMain"> 
  <div id="adMgmt" class="container tab-pane active worklistTabBody">
    <div class="page-header">
      <h1><span class="glyphicon glyphicon-user"></span> User Management</h1>
    </div>
    <%= render :partial=>"shared/flash_msg"%>
  <div class="row">   
    <div class="col-md-10  marginTop10">
     Existing Users (<%= @users.count %>)
    </div>
    <div class="col-md-2 alignRight padBtm10">
      <button type="submit" class="btn btn-default" onClick="window.location='/users/new';">+ New User</button>
    </div>
  </div>

  <div id="tableView">
  <table id="userMgmtTable" class="stripe r ow-border order-column worklistTableScroll tablesorter table-striped" cellspacing="0" width="100%">
    <thead>
      <tr class="tableHead">
        <!--<th><input type="checkbox" id="selectAll"></th>-->
        <th>Login Name (Email ID)</th> 
        <th>User Name</th> 
        <th>Reporting Supervisor</th> 
        <th>Status</th> 
        <th>Last Login</th> 
        <th>Last Password Change</th> 
        <th>Action</th> 
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <!--<td><input type="checkbox" class="checkbox1"></td>-->
        <td><%= user['email']%></td> 
        <td><%= user['username']%></td> 
        <td><%= User.find_by_id(user['parent_id']).username unless user['parent_id'].blank? %></td> 
        <td><%= user['status'] %></td> 
        <td><%= user['last_login_time'].to_date unless user['last_login_time'].blank? %></td> 
        <td><%= user['last_password_change_time'].to_date unless user['last_password_change_time'].blank?%></td> 
        <td class="text-nowrap">
          <%= link_to "Edit", "/users/modify?id=#{user['id']}"%> l <%= link_to "Delete", "/users/destroy?id=#{user['id']}", data:{confirm: 'Are you sure?'} %>
          <!--<%= link_to 'Delete', "/users/#{user['id']}", :method => "delete", data: { confirm: 'Are you sure?' } %>-->
        </td> 
      </tr>
      <% end %>
   </tbody>
  </table>
  <!-- <div class="row worklistTablePaginationHolder">

  <div class="col-md-6">
  Export as <a href="javascript:;"><img src="../images/Excel_Icon.png" border="0"></a>
  </div>

  <div class="col-md-6 worklistPagination">
  <ul class="list-inline">
  <li><a href="javascript:;"> < </a></li>
  <li><a href="javascript:;"> << </a></li>
  <li>1</li>
  <li><a href="javascript:;"> 2 </a></li>
  <li><a href="javascript:;"> 3 </a></li>
  <li><a href="javascript:;"> 4 </a></li>
  <li><a href="javascript:;"> 5 </a></li>
  <li>...</li>
  <li><a href="javascript:;"> 10 </a></li>
  <li><a href="javascript:;"> > </a></li>
  <li><a href="javascript:;"> >> </a></li>
  <li>Go to page# <input type="text" class="smallTextFld"></li>
  <li><a href="javascript:;"><img src="../images/Go_To_Page.png" border="0"></a></li>
  </ul>
  </div>

  </div>              -->
   </div>

  </div>

</div>

<script>
  $(document).ready(function(){ 
        var table = $('#userMgmtTable').DataTable( {
      scrollY:        false,
      scrollX:        false,
      scrollCollapse: true,
      paging:         true,
      searching: true,
      info:true    
    } );
    
  $("#userMgmtTable_filter input").addClass("form-control");
  $("#userMgmtTable_filter input").css({'width':'150px', 'display':'inline'});

    $('#selectAll').click(function(event) {  //on click 
      if(this.checked) { // check select status
        $('.checkbox1').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"               
        });
      }else{
        $('.checkbox1').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                       
        });         
      }
      
    });
    
    }); 
   
    

  </script>
    

app/views/users/modify.html.erb
<div class="container tab-content tabContentMain"> 
	<div id="adMgmt" class="container tab-pane active worklistTabBody">
	  <div class="page-header">
		<h1><span class="glyphicon glyphicon-user"></span> User Management</h1>
	  </div>
	  <div id="breadcrumbSection">
	    <ul class="breadcrumb">
	     <li><a href="/users">User Management</a></li>
	     <li class="active">Edit User</li>
	    </ul>
	  </div>
	 <div class="row">   
	   <div class="col-md-10  marginTop10">Edit User</div>
	 </div>
     <div class="subTabContent contentSpace">
		<%= render :partial=>"form" %>
     </div>
	</div>

</div>
<script>

$(document).ready(function() 
{ 
$('#productHeirarchyTree').sapling();
$('#locationHeirarchyTree').sapling();

$('.treeLastChild,.sapling-item').click(function() {
$('.treeLastChild,.sapling-item').removeClass('selectedFilter');
$(this).addClass('selectedFilter');

var topCat = $(".sapling-item");

if(!$(this).hasClass("sapling-expanded")){
topCat.removeClass("selectedFilter") 
}
});


$('#selectAll').click(function(event) {  //on click 
if(this.checked) { // check select status
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = true;  //select all checkboxes with class "checkbox1"               
});
}else{
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = false; //deselect all checkboxes with class "checkbox1"                       
});         
}
});

}); 
</script>

app/views/users/new.html.erb
<div class="container tab-content tabContentMain"> 
	<div id="adMgmt" class="container tab-pane active worklistTabBody">
	  <div class="page-header">
		<h1><span class="glyphicon glyphicon-user"></span> User Management</h1>
	  </div>
	  <div id="breadcrumbSection">
	    <ul class="breadcrumb">
	     <li><a href="/users">User Management</a></li>
	     <li class="active">New User</li>
	    </ul>
	  </div>
	 <div class="row">   
	   <div class="col-md-10  marginTop10">Create New User</div>
	 </div>
     <div class="subTabContent contentSpace">
		<%= render :partial=>"form" %>
     </div>
	</div>

</div>
<script>

$(document).ready(function() 
{ 
$('#productHeirarchyTree').sapling();
$('#locationHeirarchyTree').sapling();

$('.treeLastChild,.sapling-item').click(function() {
$('.treeLastChild,.sapling-item').removeClass('selectedFilter');
$(this).addClass('selectedFilter');

var topCat = $(".sapling-item");

if(!$(this).hasClass("sapling-expanded")){
topCat.removeClass("selectedFilter") 
}
});


$('#selectAll1').click(function(event) {  //on click 
if(this.checked) { // check select status
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = true;  //select all checkboxes with class "checkbox1"               
});
}else{
$('.checkbox1').each(function() { //loop through each checkbox
this.checked = false; //deselect all checkboxes with class "checkbox1"                       
});         
}
});

$('#selectAll2').click(function(event) {  //on click 
if(this.checked) { // check select status
$('.checkbox2').each(function() { //loop through each checkbox
this.checked = true;  //select all checkboxes with class "checkbox1"               
});
}else{
$('.checkbox2').each(function() { //loop through each checkbox
this.checked = false; //deselect all checkboxes with class "checkbox1"                       
});         
}
});


}); 
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.first_name %><%= @user.last_name%>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.department %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.get_role_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Logout', "/login/logout"%>